name: check-formatting

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Execute Pre-commit Hooks
      uses: pre-commit/action@v3.0.1
